-- MySQL 全数据类型测试表定义
-- 自动生成的DDL，覆盖所有数据类型和索引类型
-- Generated by tools/gen_test_data.go

DROP TABLE IF EXISTS t_int_types;
DROP TABLE IF EXISTS t_float_types;
DROP TABLE IF EXISTS t_string_types;
DROP TABLE IF EXISTS t_text_types;
DROP TABLE IF EXISTS t_binary_types;
DROP TABLE IF EXISTS t_datetime_types;
DROP TABLE IF EXISTS t_enum_set;
DROP TABLE IF EXISTS t_json_spatial;
DROP TABLE IF EXISTS t_index_types;
DROP TABLE IF EXISTS t_mixed;

-- ============================================================
-- 1. 整数类型表（含 UNSIGNED）
-- ============================================================
CREATE TABLE t_int_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_tiny        TINYINT,
    c_tiny_u      TINYINT UNSIGNED,
    c_small       SMALLINT,
    c_small_u     SMALLINT UNSIGNED,
    c_medium      MEDIUMINT,
    c_medium_u    MEDIUMINT UNSIGNED,
    c_int         INT,
    c_int_u       INT UNSIGNED,
    c_big         BIGINT,
    c_big_u       BIGINT UNSIGNED,
    c_bit         BIT(8),
    c_bool        BOOLEAN,
    PRIMARY KEY (id),
    INDEX idx_tiny (c_tiny),
    INDEX idx_big (c_big)
);

-- ============================================================
-- 2. 浮点/定点类型表
-- ============================================================
CREATE TABLE t_float_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_float       FLOAT,
    c_float_u     FLOAT UNSIGNED,
    c_double      DOUBLE,
    c_double_u    DOUBLE UNSIGNED,
    c_decimal     DECIMAL(20,6),
    c_decimal_u   DECIMAL(20,6) UNSIGNED,
    c_decimal_s   DECIMAL(5,2),
    PRIMARY KEY (id),
    INDEX idx_float (c_float),
    INDEX idx_decimal (c_decimal)
);

-- ============================================================
-- 3. 字符串类型表
-- ============================================================
CREATE TABLE t_string_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_char        CHAR(50),
    c_varchar     VARCHAR(200),
    c_binary      BINARY(20),
    c_varbinary   VARBINARY(100),
    PRIMARY KEY (id),
    INDEX idx_char (c_char),
    INDEX idx_varchar (c_varchar(50))
);

-- ============================================================
-- 4. TEXT/BLOB 类型表
-- ============================================================
CREATE TABLE t_text_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_tinytext    TINYTEXT,
    c_text        TEXT,
    c_mediumtext  MEDIUMTEXT,
    c_longtext    LONGTEXT,
    c_tinyblob    TINYBLOB,
    c_blob        BLOB,
    c_mediumblob  MEDIUMBLOB,
    c_longblob    LONGBLOB,
    PRIMARY KEY (id)
);

-- ============================================================
-- 5. BINARY 类型表
-- ============================================================
CREATE TABLE t_binary_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_binary      BINARY(16),
    c_varbinary   VARBINARY(255),
    c_tinyblob    TINYBLOB,
    c_blob        BLOB,
    c_mediumblob  MEDIUMBLOB,
    c_longblob    LONGBLOB,
    PRIMARY KEY (id)
);

-- ============================================================
-- 6. 日期时间类型表
-- ============================================================
CREATE TABLE t_datetime_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_date        DATE,
    c_time        TIME,
    c_datetime    DATETIME,
    c_timestamp   TIMESTAMP NULL DEFAULT NULL,
    c_year        YEAR,
    PRIMARY KEY (id),
    INDEX idx_date (c_date),
    INDEX idx_datetime (c_datetime)
);

-- ============================================================
-- 7. ENUM/SET 类型表
-- ============================================================
CREATE TABLE t_enum_set (
    id            INT NOT NULL AUTO_INCREMENT,
    c_enum        ENUM('small','medium','large','xlarge','special!@#'),
    c_set         SET('read','write','execute','delete','admin'),
    PRIMARY KEY (id),
    INDEX idx_enum (c_enum)
);

-- ============================================================
-- 8. JSON/空间类型表
-- ============================================================
CREATE TABLE t_json_spatial (
    id            INT NOT NULL AUTO_INCREMENT,
    c_json        JSON,
    c_point       POINT NOT NULL,
    c_geometry    GEOMETRY NOT NULL,
    PRIMARY KEY (id),
    SPATIAL INDEX idx_point (c_point),
    SPATIAL INDEX idx_geometry (c_geometry)
);

-- ============================================================
-- 9. 索引类型覆盖表
-- ============================================================
CREATE TABLE t_index_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_pk          INT NOT NULL,
    c_unique      VARCHAR(100),
    c_btree       VARCHAR(100),
    c_fulltext    TEXT,
    c_prefix      VARCHAR(255),
    c_composite1  INT,
    c_composite2  VARCHAR(50),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_pk (c_pk),
    UNIQUE INDEX uk_unique (c_unique),
    INDEX idx_btree (c_btree),
    FULLTEXT INDEX ft_fulltext (c_fulltext),
    INDEX idx_prefix (c_prefix(20)),
    INDEX idx_composite (c_composite1, c_composite2)
);

-- ============================================================
-- 10. 混合类型表（多列不同类型）
-- ============================================================
CREATE TABLE t_mixed (
    id            INT NOT NULL AUTO_INCREMENT,
    c_int         INT,
    c_bigint      BIGINT,
    c_decimal     DECIMAL(10,2),
    c_varchar     VARCHAR(100),
    c_text        TEXT,
    c_date        DATE,
    c_datetime    DATETIME,
    c_enum        ENUM('A','B','C','D'),
    c_json        JSON,
    c_bool        BOOLEAN,
    PRIMARY KEY (id),
    INDEX idx_mixed_int (c_int),
    INDEX idx_mixed_date (c_date),
    INDEX idx_mixed_enum (c_enum)
);
