package main

// MySQL 全数据类型测试数据生成器
// 生成覆盖所有数据类型、索引类型、边界值、NULL值、特殊字符的DDL和DML

import (
	"fmt"
	"math"
	"math/rand"
	"os"
	"strings"
	"time"
)

var r *rand.Rand

func init() {
	r = rand.New(rand.NewSource(time.Now().UnixNano()))
}

// 特殊字符集
var specialChars = []string{
	"!", "@", "#", "$", "%", "^", "&", "*", "(", ")",
	"~", "`", "_", "+", "=", "{", "}", "[", "]", "|",
	"\\", ":", ";", "\"", "'", "<", ">", ",", ".", "?", "/",
	"中文", "日本語", "한국어", "émoji: 🎉🔥",
	"\t", "\n", "\r",
}

func randSpecialStr() string {
	n := r.Intn(5) + 1
	parts := make([]string, n)
	for i := 0; i < n; i++ {
		parts[i] = specialChars[r.Intn(len(specialChars))]
	}
	return strings.Join(parts, "")
}

func sqlEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	s = strings.ReplaceAll(s, "\n", "\\n")
	s = strings.ReplaceAll(s, "\r", "\\r")
	s = strings.ReplaceAll(s, "\t", "\\t")
	return s
}

func main() {
	generateDDL("resources/gen_test_ddl.sql")
	generateDML("resources/gen_test_dml.sql")
	fmt.Println("Done! Generated:")
	fmt.Println("  resources/gen_test_ddl.sql")
	fmt.Println("  resources/gen_test_dml.sql")
}

func generateDDL(path string) {
	ddl := `-- MySQL 全数据类型测试表定义
-- 自动生成的DDL，覆盖所有数据类型和索引类型
-- Generated by tools/gen_test_data.go

DROP TABLE IF EXISTS t_int_types;
DROP TABLE IF EXISTS t_float_types;
DROP TABLE IF EXISTS t_string_types;
DROP TABLE IF EXISTS t_text_types;
DROP TABLE IF EXISTS t_binary_types;
DROP TABLE IF EXISTS t_datetime_types;
DROP TABLE IF EXISTS t_enum_set;
DROP TABLE IF EXISTS t_json_spatial;
DROP TABLE IF EXISTS t_index_types;
DROP TABLE IF EXISTS t_mixed;

-- ============================================================
-- 1. 整数类型表（含 UNSIGNED）
-- ============================================================
CREATE TABLE t_int_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_tiny        TINYINT,
    c_tiny_u      TINYINT UNSIGNED,
    c_small       SMALLINT,
    c_small_u     SMALLINT UNSIGNED,
    c_medium      MEDIUMINT,
    c_medium_u    MEDIUMINT UNSIGNED,
    c_int         INT,
    c_int_u       INT UNSIGNED,
    c_big         BIGINT,
    c_big_u       BIGINT UNSIGNED,
    c_bit         BIT(8),
    c_bool        BOOLEAN,
    PRIMARY KEY (id),
    INDEX idx_tiny (c_tiny),
    INDEX idx_big (c_big)
);

-- ============================================================
-- 2. 浮点/定点类型表
-- ============================================================
CREATE TABLE t_float_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_float       FLOAT,
    c_float_u     FLOAT UNSIGNED,
    c_double      DOUBLE,
    c_double_u    DOUBLE UNSIGNED,
    c_decimal     DECIMAL(20,6),
    c_decimal_u   DECIMAL(20,6) UNSIGNED,
    c_decimal_s   DECIMAL(5,2),
    PRIMARY KEY (id),
    INDEX idx_float (c_float),
    INDEX idx_decimal (c_decimal)
);

-- ============================================================
-- 3. 字符串类型表
-- ============================================================
CREATE TABLE t_string_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_char        CHAR(50),
    c_varchar     VARCHAR(200),
    c_binary      BINARY(20),
    c_varbinary   VARBINARY(100),
    PRIMARY KEY (id),
    INDEX idx_char (c_char),
    INDEX idx_varchar (c_varchar(50))
);

-- ============================================================
-- 4. TEXT/BLOB 类型表
-- ============================================================
CREATE TABLE t_text_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_tinytext    TINYTEXT,
    c_text        TEXT,
    c_mediumtext  MEDIUMTEXT,
    c_longtext    LONGTEXT,
    c_tinyblob    TINYBLOB,
    c_blob        BLOB,
    c_mediumblob  MEDIUMBLOB,
    c_longblob    LONGBLOB,
    PRIMARY KEY (id)
);

-- ============================================================
-- 5. BINARY 类型表
-- ============================================================
CREATE TABLE t_binary_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_binary      BINARY(16),
    c_varbinary   VARBINARY(255),
    c_tinyblob    TINYBLOB,
    c_blob        BLOB,
    c_mediumblob  MEDIUMBLOB,
    c_longblob    LONGBLOB,
    PRIMARY KEY (id)
);

-- ============================================================
-- 6. 日期时间类型表
-- ============================================================
CREATE TABLE t_datetime_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_date        DATE,
    c_time        TIME,
    c_datetime    DATETIME,
    c_timestamp   TIMESTAMP NULL DEFAULT NULL,
    c_year        YEAR,
    PRIMARY KEY (id),
    INDEX idx_date (c_date),
    INDEX idx_datetime (c_datetime)
);

-- ============================================================
-- 7. ENUM/SET 类型表
-- ============================================================
CREATE TABLE t_enum_set (
    id            INT NOT NULL AUTO_INCREMENT,
    c_enum        ENUM('small','medium','large','xlarge','special!@#'),
    c_set         SET('read','write','execute','delete','admin'),
    PRIMARY KEY (id),
    INDEX idx_enum (c_enum)
);

-- ============================================================
-- 8. JSON/空间类型表
-- ============================================================
CREATE TABLE t_json_spatial (
    id            INT NOT NULL AUTO_INCREMENT,
    c_json        JSON,
    c_point       POINT,
    c_geometry    GEOMETRY,
    PRIMARY KEY (id),
    SPATIAL INDEX idx_point (c_point),
    SPATIAL INDEX idx_geometry (c_geometry)
);

-- ============================================================
-- 9. 索引类型覆盖表
-- ============================================================
CREATE TABLE t_index_types (
    id            INT NOT NULL AUTO_INCREMENT,
    c_pk          INT NOT NULL,
    c_unique      VARCHAR(100),
    c_btree       VARCHAR(100),
    c_fulltext    TEXT,
    c_prefix      VARCHAR(255),
    c_composite1  INT,
    c_composite2  VARCHAR(50),
    PRIMARY KEY (id),
    UNIQUE INDEX uk_pk (c_pk),
    UNIQUE INDEX uk_unique (c_unique),
    INDEX idx_btree (c_btree),
    FULLTEXT INDEX ft_fulltext (c_fulltext),
    INDEX idx_prefix (c_prefix(20)),
    INDEX idx_composite (c_composite1, c_composite2)
);

-- ============================================================
-- 10. 混合类型表（多列不同类型）
-- ============================================================
CREATE TABLE t_mixed (
    id            INT NOT NULL AUTO_INCREMENT,
    c_int         INT,
    c_bigint      BIGINT,
    c_decimal     DECIMAL(10,2),
    c_varchar     VARCHAR(100),
    c_text        TEXT,
    c_date        DATE,
    c_datetime    DATETIME,
    c_enum        ENUM('A','B','C','D'),
    c_json        JSON,
    c_bool        BOOLEAN,
    PRIMARY KEY (id),
    INDEX idx_mixed_int (c_int),
    INDEX idx_mixed_date (c_date),
    INDEX idx_mixed_enum (c_enum)
);
`
	if err := os.WriteFile(path, []byte(ddl), 0644); err != nil {
		panic(err)
	}
	fmt.Printf("DDL written to %s\n", path)
}

func generateDML(path string) {
	var b strings.Builder
	b.WriteString("-- MySQL 全数据类型测试数据\n")
	b.WriteString("-- 自动生成的DML，覆盖边界值、NULL、空值、特殊字符\n")
	b.WriteString("-- Generated by tools/gen_test_data.go\n\n")
	b.WriteString("SET NAMES utf8mb4;\n")
	b.WriteString("SET FOREIGN_KEY_CHECKS = 0;\n\n")

	genIntTypes(&b)
	genFloatTypes(&b)
	genStringTypes(&b)
	genTextTypes(&b)
	genBinaryTypes(&b)
	genDatetimeTypes(&b)
	genEnumSet(&b)
	genJsonSpatial(&b)
	genIndexTypes(&b)
	genMixed(&b)

	b.WriteString("\nSET FOREIGN_KEY_CHECKS = 1;\n")

	if err := os.WriteFile(path, []byte(b.String()), 0644); err != nil {
		panic(err)
	}
	fmt.Printf("DML written to %s\n", path)
}

// ============================================================
// 1. 整数类型数据
// ============================================================
func genIntTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_int_types: 整数类型（含边界值、NULL、随机值）\n")
	b.WriteString("-- ============================================================\n")

	// 边界值行
	boundaryRows := []string{
		// TINYINT边界
		"(-128, 0, -32768, 0, -8388608, 0, -2147483648, 0, -9223372036854775808, 0, b'00000000', 0)",
		"(127, 255, 32767, 65535, 8388607, 16777215, 2147483647, 4294967295, 9223372036854775807, 18446744073709551615, b'11111111', 1)",
		"(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, b'00000000', 0)",
		"(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, b'00000001', 1)",
		"(-1, 1, -1, 1, -1, 1, -1, 1, -1, 1, b'11111111', 0)",
		// NULL行
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
	}
	for _, row := range boundaryRows {
		b.WriteString(fmt.Sprintf("INSERT INTO t_int_types (c_tiny, c_tiny_u, c_small, c_small_u, c_medium, c_medium_u, c_int, c_int_u, c_big, c_big_u, c_bit, c_bool) VALUES %s;\n", row))
	}

	// 随机值行 (100行)
	b.WriteString("-- 随机整数数据\n")
	for i := 0; i < 100; i++ {
		tiny := r.Intn(256) - 128
		tinyU := r.Intn(256)
		small := r.Intn(65536) - 32768
		smallU := r.Intn(65536)
		medium := r.Intn(16777216) - 8388608
		mediumU := r.Intn(16777216)
		intVal := r.Intn(2000000) - 1000000
		intU := r.Intn(2000000)
		bigVal := int64(r.Intn(2000000000)) - 1000000000
		bigU := uint64(r.Intn(2000000000))
		bitVal := r.Intn(256)
		boolVal := r.Intn(2)

		// 随机插入一些NULL
		nullMask := r.Intn(10) == 0
		if nullMask {
			tiny, small, medium = 0, 0, 0 // 不写NULL避免太复杂
		}

		b.WriteString(fmt.Sprintf("INSERT INTO t_int_types (c_tiny, c_tiny_u, c_small, c_small_u, c_medium, c_medium_u, c_int, c_int_u, c_big, c_big_u, c_bit, c_bool) VALUES (%d, %d, %d, %d, %d, %d, %d, %d, %d, %d, b'%08b', %d);\n",
			tiny, tinyU, small, smallU, medium, mediumU, intVal, intU, bigVal, bigU, bitVal, boolVal))
	}
	b.WriteString("\n")
}

// ============================================================
// 2. 浮点/定点类型数据
// ============================================================
func genFloatTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_float_types: 浮点和定点类型（含边界值、NULL、特殊值）\n")
	b.WriteString("-- ============================================================\n")

	// 边界值和特殊值
	boundaryRows := []string{
		// 极小/极大
		fmt.Sprintf("(%g, 0, %g, 0, %s, 0, 0.00)", -3.402823466e+38, -1.7976931348623157e+308, "-99999999999999.999999"),
		fmt.Sprintf("(%g, %g, %g, %g, %s, %s, 999.99)", 3.402823466e+38, 3.402823466e+38, 1.7976931348623157e+308, 1.7976931348623157e+308, "99999999999999.999999", "99999999999999.999999"),
		// 零
		"(0.0, 0.0, 0.0, 0.0, 0.000000, 0.000000, 0.00)",
		// 负零
		"(-0.0, 0.0, -0.0, 0.0, -0.000000, 0.000000, -0.01)",
		// 极小正数
		"(1.175494351e-38, 1.175494351e-38, 2.2250738585072014e-308, 2.2250738585072014e-308, 0.000001, 0.000001, 0.01)",
		// NULL
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL, NULL, NULL)",
		// 精度边界
		"(1.0, 1.0, 1.0, 1.0, 1.000000, 1.000000, 1.00)",
		"(-1.0, 0.0, -1.0, 0.0, -1.000000, 0.000000, -1.00)",
		// 大数
		"(1000000.0, 1000000.0, 1000000.0, 1000000.0, 1000000.000000, 1000000.000000, 999.99)",
	}
	for _, row := range boundaryRows {
		b.WriteString(fmt.Sprintf("INSERT INTO t_float_types (c_float, c_float_u, c_double, c_double_u, c_decimal, c_decimal_u, c_decimal_s) VALUES %s;\n", row))
	}

	// 随机值 (100行)
	b.WriteString("-- 随机浮点数据\n")
	for i := 0; i < 100; i++ {
		f := r.Float64()*2000 - 1000
		fU := r.Float64() * 2000
		d := r.Float64()*2000 - 1000
		dU := r.Float64() * 2000
		dec := r.Float64()*200000 - 100000
		decU := r.Float64() * 200000
		decS := r.Float64()*1999.98 - 999.99

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_float_types (c_float, c_float_u, c_double, c_double_u, c_decimal, c_decimal_u, c_decimal_s) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_float_types (c_float, c_float_u, c_double, c_double_u, c_decimal, c_decimal_u, c_decimal_s) VALUES (%.6f, %.6f, %.6f, %.6f, %.6f, %.6f, %.2f);\n",
				f, math.Abs(fU), d, math.Abs(dU), dec, math.Abs(decU), decS))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 3. 字符串类型数据
// ============================================================
func genStringTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_string_types: 字符串类型（含空值、NULL、特殊字符）\n")
	b.WriteString("-- ============================================================\n")

	// 特殊值
	specialRows := []string{
		// 空字符串
		"('', '', x'', x'')",
		// NULL
		"(NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL)",
		// 特殊字符
		`('!@#$%^&*()', '!@#$%^&*()_+-=[]{}|;:,.<>?', x'21402324', x'2140232425')`,
		`('中文测试', '中文测试データテスト', x'E4B8ADE69687', x'E4B8ADE69687')`,
		`('タブ\t改行\n', 'タブ\t改行\nリターン\r', x'09', x'09')`,
		`('シングル''クォート', 'ダブル"クォート', x'27', x'22')`,
		// 边界长度
		"(REPEAT('A', 50), REPEAT('B', 200), REPEAT(x'41', 20), REPEAT(x'42', 100))",
		"(REPEAT('Z', 50), REPEAT('Z', 200), REPEAT(x'5A', 20), REPEAT(x'5A', 100))",
		// Unicode
		`('émojis: 🎉🔥💯', 'Café résumé naïve', x'C3A9', x'C3A9')`,
	}
	for _, row := range specialRows {
		b.WriteString(fmt.Sprintf("INSERT INTO t_string_types (c_char, c_varchar, c_binary, c_varbinary) VALUES %s;\n", row))
	}

	// 随机值 (120行)
	b.WriteString("-- 随机字符串数据\n")
	charsets := []string{
		"abcdefghijklmnopqrstuvwxyz",
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ",
		"0123456789",
		"!@#$%^&*()_+-=[]{}|;:',.<>?/",
		"áéíóúñüç日本語中文한국어",
	}
	for i := 0; i < 120; i++ {
		charLen := r.Intn(50) + 1
		varcharLen := r.Intn(200) + 1
		charVal := randString(charLen, charsets)
		varcharVal := randString(varcharLen, charsets)

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_string_types (c_char, c_varchar, c_binary, c_varbinary) VALUES (NULL, NULL, NULL, NULL);\n")
		} else if r.Intn(5) == 0 {
			b.WriteString("INSERT INTO t_string_types (c_char, c_varchar, c_binary, c_varbinary) VALUES ('', '', x'', x'');\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_string_types (c_char, c_varchar, c_binary, c_varbinary) VALUES ('%s', '%s', x'%s', x'%s');\n",
				sqlEscape(charVal), sqlEscape(varcharVal), randHex(20), randHex(r.Intn(100)+1)))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 4. TEXT/BLOB 类型数据
// ============================================================
func genTextTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_text_types: TEXT和BLOB类型\n")
	b.WriteString("-- ============================================================\n")

	// 特殊值
	b.WriteString("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES ('', '', '', '', x'', x'', x'', x'');\n")
	b.WriteString("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString(`INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES ('!@#$%^&*()_+', '!@#$%^&*()_+中文', '!@#$%^&*()_+special chars !@#$%^&*()_+', '!@#$%^&*()_+very long text with special chars', x'2140232425', x'2140232425', x'2140232425', x'2140232425');` + "\n")
	b.WriteString(`INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES ('日本語テスト', '한국어 테스트 데이터', '中文测试数据', 'émoji test 🎉🔥💯', x'E4B8AD', x'E4B8AD', x'E4B8AD', x'E4B8AD');` + "\n")

	// 随机值 (100行)
	b.WriteString("-- 随机TEXT/BLOB数据\n")
	for i := 0; i < 100; i++ {
		tinyLen := r.Intn(200) + 1
		textLen := r.Intn(500) + 1
		tinyVal := randString(tinyLen, []string{"abcdefghijklmnopqrstuvwxyz0123456789!@#$%"})
		textVal := randString(textLen, []string{"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"})

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_text_types (c_tinytext, c_text, c_mediumtext, c_longtext, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES ('%s', '%s', '%s', '%s', x'%s', x'%s', x'%s', x'%s');\n",
				sqlEscape(tinyVal), sqlEscape(textVal), sqlEscape(textVal), sqlEscape(textVal+textVal),
				randHex(r.Intn(200)+1), randHex(r.Intn(200)+1), randHex(r.Intn(200)+1), randHex(r.Intn(200)+1)))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 5. BINARY 类型数据
// ============================================================
func genBinaryTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_binary_types: BINARY和BLOB类型\n")
	b.WriteString("-- ============================================================\n")

	b.WriteString("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (x'', x'', x'', x'', x'', x'');\n")
	b.WriteString("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL);\n")

	for i := 0; i < 100; i++ {
		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (NULL, NULL, NULL, NULL, NULL, NULL);\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_binary_types (c_binary, c_varbinary, c_tinyblob, c_blob, c_mediumblob, c_longblob) VALUES (x'%s', x'%s', x'%s', x'%s', x'%s', x'%s');\n",
				randHex(16), randHex(r.Intn(255)+1), randHex(r.Intn(200)+1),
				randHex(r.Intn(200)+1), randHex(r.Intn(200)+1), randHex(r.Intn(200)+1)))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 6. 日期时间类型数据
// ============================================================
func genDatetimeTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_datetime_types: 日期时间类型（含边界值、NULL）\n")
	b.WriteString("-- ============================================================\n")

	// 边界值和特殊值
	boundaryRows := []string{
		// 零值
		"('0001-01-01', '-838:59:59', '1000-01-01 00:00:00', '1970-01-01 00:00:01', 1901)",
		"('9999-12-31', '838:59:59', '9999-12-31 23:59:59', '2038-01-19 03:14:07', 2155)",
		// 零日期
		"('0000-00-00', '00:00:00', '0000-00-00 00:00:00', NULL, 0000)",
		// NULL
		"(NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL)",
		"(NULL, NULL, NULL, NULL, NULL)",
		// 特殊日期
		"('2000-02-29', '12:00:00', '2000-02-29 12:00:00', '2000-02-29 12:00:00', 2000)",
		"('1970-01-01', '00:00:01', '1970-01-01 00:00:01', '1970-01-01 00:00:01', 1970)",
		"('2038-01-19', '23:59:59', '2038-01-19 03:14:07', '2038-01-19 03:14:07', 2038)",
		// 当前时间
		"(CURDATE(), CURTIME(), NOW(), NOW(), YEAR(CURDATE()))",
	}
	for _, row := range boundaryRows {
		b.WriteString(fmt.Sprintf("INSERT INTO t_datetime_types (c_date, c_time, c_datetime, c_timestamp, c_year) VALUES %s;\n", row))
	}

	// 随机值 (100行)
	b.WriteString("-- 随机日期时间数据\n")
	for i := 0; i < 100; i++ {
		year := 1970 + r.Intn(70)
		month := r.Intn(12) + 1
		day := r.Intn(28) + 1 // 安全地避免无效日期
		hour := r.Intn(24)
		minute := r.Intn(60)
		sec := r.Intn(60)

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_datetime_types (c_date, c_time, c_datetime, c_timestamp, c_year) VALUES (NULL, NULL, NULL, NULL, NULL);\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_datetime_types (c_date, c_time, c_datetime, c_timestamp, c_year) VALUES ('%04d-%02d-%02d', '%02d:%02d:%02d', '%04d-%02d-%02d %02d:%02d:%02d', '%04d-%02d-%02d %02d:%02d:%02d', %d);\n",
				year, month, day, hour, minute, sec,
				year, month, day, hour, minute, sec,
				year, month, day, hour, minute, sec,
				year))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 7. ENUM/SET 类型数据
// ============================================================
func genEnumSet(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_enum_set: ENUM和SET类型\n")
	b.WriteString("-- ============================================================\n")

	enumVals := []string{"small", "medium", "large", "xlarge", "special!@#"}
	setVals := []string{"read", "write", "execute", "delete", "admin"}

	// 边界值和特殊值
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES (NULL, NULL);\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES (NULL, NULL);\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES (NULL, NULL);\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('small', '');\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('special!@#', 'read,write,execute,delete,admin');\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('medium', 'read');\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('large', 'read,write');\n")
	b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('xlarge', 'admin');\n")

	// 随机值 (100行)
	b.WriteString("-- 随机ENUM/SET数据\n")
	for i := 0; i < 100; i++ {
		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_enum_set (c_enum, c_set) VALUES (NULL, NULL);\n")
		} else {
			enumVal := enumVals[r.Intn(len(enumVals))]
			// 随机组合SET值
			n := r.Intn(6)
			setParts := make([]string, 0)
			for j := 0; j < n; j++ {
				sv := setVals[r.Intn(len(setVals))]
				// 避免重复
				found := false
				for _, sp := range setParts {
					if sp == sv {
						found = true
						break
					}
				}
				if !found {
					setParts = append(setParts, sv)
				}
			}
			setStr := strings.Join(setParts, ",")
			b.WriteString(fmt.Sprintf("INSERT INTO t_enum_set (c_enum, c_set) VALUES ('%s', '%s');\n", enumVal, setStr))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 8. JSON/空间类型数据
// ============================================================
func genJsonSpatial(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_json_spatial: JSON和空间类型\n")
	b.WriteString("-- ============================================================\n")

	// 特殊值
	b.WriteString("INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES (NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES (NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES (NULL, NULL, NULL);\n")
	b.WriteString(`INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('{}', ST_GeomFromText('POINT(0 0)'), ST_GeomFromText('POINT(0 0)'));` + "\n")
	b.WriteString(`INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('{"key": "value", "num": 42, "arr": [1,2,3]}', ST_GeomFromText('POINT(1 1)'), ST_GeomFromText('POINT(1 1)'));` + "\n")
	b.WriteString(`INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('{"special": "!@#$%^&*()"}', ST_GeomFromText('POINT(-180 -90)'), ST_GeomFromText('LINESTRING(0 0, 1 1, 2 2)'));` + "\n")
	b.WriteString(`INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('{"unicode": "中文测试🎉"}', ST_GeomFromText('POINT(180 90)'), ST_GeomFromText('POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))'));` + "\n")
	b.WriteString(`INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('{"nested": {"a": {"b": {"c": 1}}}}', ST_GeomFromText('POINT(12.34 56.78)'), ST_GeomFromText('POINT(12.34 56.78)'));` + "\n")

	// 随机值 (100行)
	b.WriteString("-- 随机JSON/空间数据\n")
	for i := 0; i < 100; i++ {
		x := r.Float64()*360 - 180
		y := r.Float64()*180 - 90
		nullMask := r.Intn(10) == 0

		if nullMask {
			b.WriteString("INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES (NULL, NULL, NULL);\n")
		} else {
			jsonVal := fmt.Sprintf(`{"id": %d, "x": %.4f, "y": %.4f, "name": "%s"}`,
				i, x, y, sqlEscape(randString(r.Intn(20)+1, []string{"abcdefghijklmnopqrstuvwxyz0123456789"})))
			b.WriteString(fmt.Sprintf("INSERT INTO t_json_spatial (c_json, c_point, c_geometry) VALUES ('%s', ST_GeomFromText('POINT(%.4f %.4f)'), ST_GeomFromText('POINT(%.4f %.4f)'));\n",
				sqlEscape(jsonVal), x, y, x, y))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 9. 索引类型覆盖表
// ============================================================
func genIndexTypes(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_index_types: 索引类型覆盖（PRIMARY/UNIQUE/BTREE/FULLTEXT/PREFIX/COMPOSITE）\n")
	b.WriteString("-- ============================================================\n")

	// 特殊值
	b.WriteString("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (0, '', '', '', '', 0, '');\n")
	b.WriteString("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (1, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (2, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (3, '!@#$%^&*()', 'special chars test', 'This is a fulltext search test with special chars !@#$%', 'prefix test value here', 1, 'composite');\n")
	b.WriteString("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (4, '中文唯一键', '中文索引', '中文全文搜索测试数据', '中文前缀索引测试', 2, '中文');\n")

	// 随机值 (100行)
	b.WriteString("-- 随机索引数据\n")
	for i := 0; i < 100; i++ {
		pk := i + 100
		unique := fmt.Sprintf("unique_%d_%s", i, randString(5, []string{"abcdefghijklmnopqrstuvwxyz"}))
		btree := fmt.Sprintf("btree_%d_%s", i, randString(10, []string{"abcdefghijklmnopqrstuvwxyz0123456789"}))
		fulltext := fmt.Sprintf("word%d word%d word%d test search fulltext", r.Intn(100), r.Intn(100), r.Intn(100))
		prefix := fmt.Sprintf("prefix_%s_%d", randString(30, []string{"abcdefghijklmnopqrstuvwxyz"}), i)
		comp1 := r.Intn(100)
		comp2 := fmt.Sprintf("comp_%d", r.Intn(50))

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString(fmt.Sprintf("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (%d, NULL, NULL, NULL, NULL, NULL, NULL);\n", pk))
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_index_types (c_pk, c_unique, c_btree, c_fulltext, c_prefix, c_composite1, c_composite2) VALUES (%d, '%s', '%s', '%s', '%s', %d, '%s');\n",
				pk, sqlEscape(unique), sqlEscape(btree), sqlEscape(fulltext), sqlEscape(prefix), comp1, comp2))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 10. 混合类型表
// ============================================================
func genMixed(b *strings.Builder) {
	b.WriteString("-- ============================================================\n")
	b.WriteString("-- t_mixed: 混合类型表（多列不同类型组合）\n")
	b.WriteString("-- ============================================================\n")

	// 特殊值
	b.WriteString("INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString("INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
	b.WriteString(`INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (-2147483648, -9223372036854775808, -99999999.99, '!@#$%^&*()', '!@#special', '0001-01-01', '1000-01-01 00:00:00', 'A', '{"min": true}', 0);` + "\n")
	b.WriteString(`INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (2147483647, 9223372036854775807, 99999999.99, '中文数据', '中文文本', '9999-12-31', '9999-12-31 23:59:59', 'D', '{"max": true}', 1);` + "\n")
	b.WriteString(`INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (0, 0, 0.00, '', '', '0000-00-00', '0000-00-00 00:00:00', 'B', '{}', 0);` + "\n")

	// 随机值 (100行)
	b.WriteString("-- 随机混合数据\n")
	enumVals := []string{"A", "B", "C", "D"}
	for i := 0; i < 100; i++ {
		intVal := r.Intn(2000000) - 1000000
		bigVal := int64(r.Intn(2000000000)) - 1000000000
		decVal := r.Float64()*200000 - 100000
		varcharVal := randString(r.Intn(100)+1, []string{"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%"})
		textVal := randString(r.Intn(200)+1, []string{"abcdefghijklmnopqrstuvwxyz0123456789"})
		year := 1970 + r.Intn(70)
		month := r.Intn(12) + 1
		day := r.Intn(28) + 1
		hour := r.Intn(24)
		minute := r.Intn(60)
		sec := r.Intn(60)
		enumVal := enumVals[r.Intn(len(enumVals))]
		jsonVal := fmt.Sprintf(`{"i": %d, "s": "%s"}`, i, randString(5, []string{"abcdef"}))
		boolVal := r.Intn(2)

		nullMask := r.Intn(10) == 0
		if nullMask {
			b.WriteString("INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);\n")
		} else {
			b.WriteString(fmt.Sprintf("INSERT INTO t_mixed (c_int, c_bigint, c_decimal, c_varchar, c_text, c_date, c_datetime, c_enum, c_json, c_bool) VALUES (%d, %d, %.2f, '%s', '%s', '%04d-%02d-%02d', '%04d-%02d-%02d %02d:%02d:%02d', '%s', '%s', %d);\n",
				intVal, bigVal, decVal,
				sqlEscape(varcharVal), sqlEscape(textVal),
				year, month, day, year, month, day, hour, minute, sec,
				enumVal, sqlEscape(jsonVal), boolVal))
		}
	}
	b.WriteString("\n")
}

// ============================================================
// 工具函数
// ============================================================

func randString(n int, charsets []string) string {
	all := strings.Join(charsets, "")
	result := make([]byte, n)
	for i := 0; i < n; i++ {
		result[i] = all[r.Intn(len(all))]
	}
	return string(result)
}

func randHex(n int) string {
	const hex = "0123456789ABCDEF"
	result := make([]byte, n*2)
	for i := 0; i < n*2; i++ {
		result[i] = hex[r.Intn(16)]
	}
	return string(result)
}
